// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28hleCP9ioeNsFrU6RjkHNsfzDcD9Uf8',
    appId: '1:400597232968:web:dc7789a55541a64adb977d',
    messagingSenderId: '400597232968',
    projectId: 'file-tracking-system-c8b88',
    authDomain: 'file-tracking-system-c8b88.firebaseapp.com',
    storageBucket: 'file-tracking-system-c8b88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaTbPOXDIw043EmE38-ItkQt97hB0-kPE',
    appId: '1:400597232968:android:b7c90ef5ae093997db977d',
    messagingSenderId: '400597232968',
    projectId: 'file-tracking-system-c8b88',
    storageBucket: 'file-tracking-system-c8b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCACUqMQPdhDf_4ZVLolMCoZQJYF4oG8cU',
    appId: '1:400597232968:ios:5e616c90a5f69285db977d',
    messagingSenderId: '400597232968',
    projectId: 'file-tracking-system-c8b88',
    storageBucket: 'file-tracking-system-c8b88.appspot.com',
    iosClientId: '400597232968-f6gflb0di5tn3n63e145e37horc2clcp.apps.googleusercontent.com',
    iosBundleId: 'com.hackathon.fts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCACUqMQPdhDf_4ZVLolMCoZQJYF4oG8cU',
    appId: '1:400597232968:ios:5e616c90a5f69285db977d',
    messagingSenderId: '400597232968',
    projectId: 'file-tracking-system-c8b88',
    storageBucket: 'file-tracking-system-c8b88.appspot.com',
    iosClientId: '400597232968-f6gflb0di5tn3n63e145e37horc2clcp.apps.googleusercontent.com',
    iosBundleId: 'com.hackathon.fts',
  );
}
